version: 2.1

jobs:
  build:
    docker:
      - image: archlinux/base

    steps:
      - checkout

      - run:
          name: Install dependencies
          command: |
            pacman -Syu --noconfirm
            pacman -S --noconfirm base-devel git sudo 

      # Build the package
      - run:
          name: Build package
          command: |
            useradd -m builder && echo "Added user builder"
            echo "builder ALL=(ALL) NOPASSWD: ALL" | tee -a /etc/sudoers
            echo "root ALL=(ALL) NOPASSWD: ALL" | tee -a /etc/sudoers
            git clone https://github.com/omansh-krishn/build-materialgram.git /home/builder/build && cd /home/builder/build
            sudo -u builder makepkg --syncdeps --noconfirm --needed

      - run:
          name: Upload 
          command: |
            curl --upload /home/build/**zst https://free.keep.sh

workflows:
  version: 2
  build:
    jobs:
      - build

