version: 2.1

jobs:
  build:
    docker:
      - image: archlinux:latest

    steps:
      - checkout

      - run:
          name: Install dependencies
          command: |
            pacman-key --init && pacman-key --populate
            pacman -Syu base-devel git --noconfirm --quiet

      # Build the package
      - run:
          name: Build package
          command: |
            useradd -m builder
            su builder -c "git clone https://github.com/omansh-krishn/build-materialgram.git /home/builder/build && cd /home/builder/build && makepkg --syncdeps --noconfirm --needed"

      - run:
          name: Upload 
          command: |
            curl --upload /home/build/**zst https://transfer.sh

workflows:
  version: 2
  build:
    jobs:
      - build

