name: Build Package

on:
  push:
    tags:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: omanshkrishn/materialgram:latest

    steps:
      - name: Update System
        run: pacman -Syu --noconfirm

      - name: Set Tag Name
        run: echo "TAGNAME=$(echo ${{ github.ref }} | cut -d '/' -f3)" >> $GITHUB_ENV 

      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: 'recursive'
          path: '/home/builder/materialgram'

      - name: Build package
        run: |
          echo "DEBUG" && pwd && ls && echo ${{ env.TAGNAME }} && echo materialgram-${{ env.TAGNAME }} && echo materialgram-${{env.TAGNAME}} && echo "DEBUG"
          cmake \
           -B build \
           -G Ninja \
           -DCMAKE_INSTALL_PREFIX="/usr" \
           -DCMAKE_BUILD_TYPE=Release \
           -DTDESKTOP_API_ID=${{ secrets.API_ID }} \
           -DTDESKTOP_API_HASH=${{ secrets.API_HASH }} \
           -DDESKTOP_APP_DISABLE_AUTOUPDATE=True \
           -DCMAKE_INTERPROCEDURAL_OPTIMIZATION=ON 
          ninja -C build -j$(nproc --all) 

      - name: Make Tarball
        run: |
          pwd && echo ${{ env.TAGNAME }}
          mkdir fakeroot && DESTDIR=$(pwd)/fakeroot ninja -C build install && cd fakeroot 
          tar -czvf materialgram-${{ env.TAGNAME }}.tar.gz usr  
          ls  

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: materialgram-${{ env.TAGNAME }}
          path: /home/builder/materialgram/fakeroot/materialgram-${{ env.TAGNAME }}.tar.gz

      - name: Upload artifact to Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          name: ${{ env.TAGNAME }}
          token: ${{ secrets.PAT }}
          files: /home/builder/materialgram/fakeroot/materialgram-${{ env.TAGNAME }}.tar.gz
