name: Build Package

on:
  push:
      tags:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: omanshkrishn/materialgram:latest

    steps:
      - name: Build package
        run: |
          git clone https://github.com/kukuruzka165/materialgram --recursive && cd materialgram
          cmake \
            -B build \
            -G Ninja \
            -DCMAKE_INSTALL_PREFIX="/usr" \
            -DCMAKE_BUILD_TYPE=Release \
            -DTDESKTOP_API_ID=611335 \
            -DTDESKTOP_API_HASH=d524b414d21f4d37f08684c1df41ac9c \
            -DDESKTOP_APP_DISABLE_AUTOUPDATE=True \
            -DCMAKE_INTERPROCEDURAL_OPTIMIZATION=ON
          ninja -C build -j$(nproc --all)
          echo ${{ env.GITHUB_REF }} && export TAG=${{ env.GITHUB_REF }}
          mkdir fakeroot && DESTDIR=$(pwd)/fakeroot ninja -C build install
          tar -czvf materialgram-$TAG.tar.gz fakeroot/usr && ls && cp **tar.gz ..

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: materialgram-${{ env.GITHUB_REF }}
          path: /home/builder/**tar.gz
      








