name: Build Package

on:
  push:
    tags:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    container:
      image: omanshkrishn/materialgram:latest

    steps:
      - name: Build package
        run: |
          [ -d "/home/builder" ] && cd /home/builder || { mkdir -p /home/builder && cd /home/builder; }
          echo "TAGNAME=$(echo ${{ github.ref }} | cut -d '/' -f3)" >> $GITHUB_ENV && echo $TAGNAME
          TAGNAME=$(echo ${{ github.ref }} | cut -d '/' -f3) && echo $TAGNAME && echo "app-$TAGNAME"
          git clone https://github.com/kukuruzka165/materialgram --recursive && cd materialgram 
          cmake \
            -B build \
            -G Ninja \
            -DCMAKE_INSTALL_PREFIX="/usr" \
            -DCMAKE_BUILD_TYPE=Release \
            -DTDESKTOP_API_ID=611335 \
            -DTDESKTOP_API_HASH=d524b414d21f4d37f08684c1df41ac9c \
            -DDESKTOP_APP_DISABLE_AUTOUPDATE=True \
            -DCMAKE_INTERPROCEDURAL_OPTIMIZATION=ON 
          ninja -C build -j$(nproc --all) 
          mkdir fakeroot && DESTDIR=$(pwd)/fakeroot ninja -C build install 
          tar -czvf "materialgram-$(echo $GITHUB_REF | cut -d '/' -f3).tar.gz" fakeroot/usr && cp "materialgram-$(echo $GITHUB_REF | cut -d '/' -f3).tar.gz" .. && ls && echo 'DEBUGBUGBUG' && ls ..

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: materialgram-${{ env.TAGNAME }}
          path: /home/builder/**tar.gz

      - name: Upload to Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          name: ${{ env.TAGNAME }} 
          token: ${{ secrets.GITHUB_TOKEN }}
          files: /home/builder/**tar.gz

